version: "3"
services:

  uwsgi:
    image: asatai95/docker_uwsgi
    build: ./app
    volumes:
      - ./app:/var/www
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    image: asatai95/docker_nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ".:/var/www"
    links:
      - uwsgi
    ports:
      - "8080:80"
    environment:
      TZ: "Asia/Tokyo"

  db:
    image: asatai95/docker_db
    build: ./db/
    volumes:
      - ./db/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./db/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: asatai951156
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: docker
    ports:
      - "3306:3306"
